from abc import ABC, abstractmethod
from typing import List, Dict, Any, Callable, get_type_hints
from pydantic import BaseModel
import inspect
import re


def tool_action(name: str = None, description: str = None):
    """装饰器: 标记一个方法为可展开的工具
    
    使用示例:
        @tool_action("memory_add", "添加新的记忆")
        def _add_memory(self, content: str, importance: float = 0.5) -> str:
            '''添加新的记忆
            
            Args:
                content: 记忆内容
                importance: 重要性分数, 0-1之间, 默认为0.5
            '''
            pass
    """

    def decorator(func: Callable):
        func._is_tool_action = True
        func._tool_name = name
        func._tool_description = description
        return func

    return decorator

class ToolParameter(BaseModel):
    """工具参数定义"""
    name: str
    type: str
    description: str
    required: bool = True
    default: Any = None

class Tool(ABC):
    """工具基类
    
    支持两种使用模式:
        1. 普通模式: 工具作为单一实体
        2. 可扩展模式: 工具可以展开为多个独立的子工具(每个工具对应一个功能)
    
    可扩展模式支持两种实现方式:
        1. 手动定义子工具类
        2. 使用 @tool_action 装饰器自动生成(推荐)
    """

    def __init__(self, name: str, description: str, expandable: bool = False):
        """初始化工具
        
        Args:
            name: 工具名称
            description: 工具描述
            expandable: 是否可展开为多个子工具
        """
        self.name = name
        self.description = description
        self.expandable = expandable

    @abstractmethod
    def run(self, parameters: Dict[str, Any]) -> str:
        """执行工具"""
        pass

    @abstractmethod
    def get_parameters(self) -> List[ToolParameter]:
        """获取工具参数定义"""
        pass
    
    def get_expanded_tools(self) -> List['Tool']:
        """获取展开后的子工具列表
        
        默认实现: 从标记了 @tool_action 的方法自动生成子工具
        子类可以重写此方法实现自定义的展开逻辑

        Returns:
            若工具支持展开, 则返回子工具列表, 否则返回None
        """

        if not self.expandable:
            return None
        
        # 自动从装饰器标记的方法生成工具
        tools = []
        for name, method in inspect.getmembers(self, predicate=inspect.ismethod):
            if hasattr(method, '_is_tool_action'):
                tool = AutoGeneratedTool(
                    parent=self,
                    method=method,
                    name=method._tool_name,
                    description=method._tool_description
                )
                tools.append(tool)

        return tools if tools else None

    def to_dict(self) -> Dict[str, Any]:
        """将工具信息转换成字典格式"""
        return {
            "name": self.name,
            "description": self.description,
            "parameters": [param.model_dump() for param in self.get_parameters()]
        }
    
    def validate_parameters(self, parameters: Dict[str, Any]) -> bool:
        return True  # TODO: NotImplementation
    
    def to_openai_schema(self) -> Dict[str, Any]:
        pass

    def __str__(self) -> str:
        return f"Tool(name={self.name})"
    
    def __repr__(self) -> str:
        return self.__str__()


class AutoGeneratedTool(Tool):
    """自动生成的子工具类, 默认由父工具通过 @tool_action 标记的方法生成"""

    def __init__(self, parent: Tool, method: Callable, name: str = None, description: str = None):
        """初始化自动生成的子工具
        
        Args:
            parent: 父工具实例
            method: 需要被展开为工具的方法, 默认由 @tool_action 装饰
            name: 工具名称, 默认为方法名
            description: 工具描述, 默认从docstring获取
        """
        self.parent = parent
        self.method = method
       
        # 生成工具名称
        if name is None:
            method_name = method.__name__.lstrip('_')  # 去掉可能的下划线前缀
            name = f"{parent.name}_{method_name}"
        
        # 生成工具描述
        if description is None:
            description = self._extract_description_from_docstring()
        
        super().__init__(name=name, description=description)

        # 自动解析参数
        self._parameters = self._parse_parameters()
    
    def _extract_description_from_docstring(self) -> str:
        """从方法的 docstring 提取工具描述"""
        doc = inspect.getdoc(self.method)
        if not doc:
            return f"执行 {self.method.__name__}"

        # 提取第一行作为描述
        lines = doc.split('\n')
        for line in lines:
            line = line.strip()
            if line and not line.startswith('Args:') and not line.startswith('Returns:'):
                return line

        return f"执行 {self.method.__name__}"

    def _parse_parameters(self) -> List[ToolParameter]:
        """从方法签名和 docstring 自动提取工具参数"""
        sig = inspect.signature(self.method)
        type_hints = get_type_hints(self.method)
        docstring = inspect.getdoc(self.method) or ""

        # 从 docstring 解析参数描述
        param_descriptions = self._parse_param_descriptions(docstring) 

        parameters = []
        for param_name, param in sig.parameters.items():
            if param_name == 'self':
                continue  
            
            # 获取类型
            param_type_hint = type_hints.get(param_name, str)
            param_type = self._python_type_to_tool_type(param_type_hint)

            # 判断是否必需
            required = param.default == inspect.Parameter.empty
            default = None if required else param.default

            # 获取描述
            description = param_descriptions.get(param_name, f"参数 {param_name}")

            parameters.append(ToolParameter(
                name=param_name,
                type=param_type,
                description=description,
                required=required,
                default=default
            ))

        return parameters
    
    def _parse_param_descriptions(self, docstring: str) -> Dict[str, str]:
        """从 docstring 解析参数描述

        支持格式:
            Args:
                param_name_a (type): 参数param_name_a的描述
                param_name_b (type): 参数param_name_b的描述
                ...
        
        Returns:
            参数描述字典, key为参数名, value为参数对应的描述
        """
        descriptions = {}

        # 查找 Args: 部分
        args_match = re.search(r'Args:\s*\n(.*?)(?:\n\s*\n|Returns:|$)', docstring, re.DOTALL)
        if not args_match:
            return descriptions

        args_section = args_match.group(1)

        # 解析每个参数
        # 匹配格式: param_name: 描述 或 param_name (type): 描述
        param_pattern = r'^\s*(\w+)(?:\s*\([^)]+\))?\s*:\s*(.+?)(?=^\s*\w+\s*(?:\([^)]+\))?\s*:|$)'
        matches = re.finditer(param_pattern, args_section, re.MULTILINE | re.DOTALL)

        for match in matches:
            param_name = match.group(1).strip()
            param_desc = match.group(2).strip()
            # 清理描述中的多余空白
            param_desc = re.sub(r'\s+', ' ', param_desc)
            descriptions[param_name] = param_desc

        return descriptions

    def _python_type_to_tool_type(self, py_type) -> str:
        """将 Python 类型转换为工具类型字符串"""
        # 处理泛型类型
        origin = getattr(py_type, '__origin__', None)
        if origin is not None:
            if origin is list:
                return "array"
            elif origin is dict:
                return "object"

        # 处理基本类型
        type_map = {
            str: "string",
            int: "integer",
            float: "number",
            bool: "boolean",
            list: "array",
            dict: "object",
        }

        return type_map.get(py_type, "string")

    def get_parameters(self) -> List[ToolParameter]:
        """获取参数列表"""
        return self._parameters
    
    def run(self, parameters: Dict[str, Any]) -> str:
        """调用父工具的方法执行"""
        return self.method(**parameters)